# Generated by Django 5.2.12 on 2026-03-18 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '👦 Парень'), ('female', '👧 Девушка')], max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='search_gender',
            field=models.CharField(blank=True, choices=[('male', '👦 Парень'), ('female', '👧 Девушка')], help_text='Какой пол ищет пользователь (null = любой)', max_length=10, null=True, verbose_name='Ищу пол'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(help_text='True = 👍, False = 👎', verbose_name='Лайк')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='chat.chatsession', verbose_name='Чат-сессия')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='users.telegramuser', verbose_name='От кого')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='users.telegramuser', verbose_name='Кому')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'ordering': ['-created_at'],
                'unique_together': {('from_user', 'to_user', 'chat_session')},
            },
        ),
    ]
