# Generated by Django 5.2.12 on 2026-03-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_telegramuser_gender_telegramuser_search_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название канала')),
                ('channel_username', models.CharField(help_text='Например: @mychannel (с @)', max_length=255, unique=True, verbose_name='Username канала')),
                ('invite_link', models.URLField(help_text='https://t.me/mychannel или приватная ссылка', verbose_name='Ссылка на канал')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные каналы не проверяются', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Обязательный канал',
                'verbose_name_plural': 'Обязательные каналы',
                'ordering': ['title'],
            },
        ),
    ]
