# Generated by Django 5.2.12 on 2026-03-20 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_requiredchannel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelSubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_username', models.CharField(db_index=True, max_length=255, verbose_name='Username канала')),
                ('channel_title', models.CharField(max_length=255, verbose_name='Название канала')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата подписки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_events', to='users.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие подписки',
                'verbose_name_plural': 'Статистика подписок',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'channel_username')},
            },
        ),
    ]
