# Generated by Django 5.2.12 on 2026-03-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_channelsubscriptionevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название бота')),
                ('bot_username', models.CharField(help_text='Например: @mybot (с @)', max_length=255, unique=True, verbose_name='Username бота')),
                ('invite_link', models.URLField(help_text='https://t.me/mybot', verbose_name='Ссылка на бота')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные боты не проверяются', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Обязательный бот',
                'verbose_name_plural': 'Обязательные боты',
                'ordering': ['title'],
            },
        ),
    ]
