# Generated by Django 5.2.12 on 2026-03-21 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_requiredbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='Кто пригласил этого пользователя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='users.telegramuser', verbose_name='Приглашён пользователем'),
        ),
    ]
