# Generated by Django 5.2.12 on 2026-03-21 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_telegramuser_referred_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Instagram реклама, VK пост', max_length=255, verbose_name='Название кампании')),
                ('code', models.CharField(blank=True, help_text='Используется в ссылке. Оставьте пустым — сгенерируется автоматически.', max_length=64, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Заметки: где размещена реклама, бюджет и т.д.', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Рекламная кампания',
                'verbose_name_plural': 'Рекламные кампании',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='referred_by',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Через какую рекламную кампанию пришёл пользователь', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.referralcampaign', verbose_name='Кампания'),
        ),
    ]
