# Generated by Django 5.2.12 on 2026-03-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_referralcampaign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referralcampaign',
            options={'ordering': ['-created_at'], 'verbose_name': 'Реферальная ссылка', 'verbose_name_plural': 'Реферальные ссылки'},
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='bots_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Когда пользователь последний раз подтвердил запуск обязательных ботов', null=True, verbose_name='Боты подтверждены'),
        ),
        migrations.AlterField(
            model_name='referralcampaign',
            name='description',
            field=models.TextField(blank=True, help_text='Где размещаете, какой аудиторий и т.д.', verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='referralcampaign',
            name='name',
            field=models.CharField(help_text='Например: Instagram, VK, Telegram-канал', max_length=255, verbose_name='Название'),
        ),
    ]
