# Generated by Django 5.2.12 on 2026-03-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_telegramuser_bots_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Обновляется при любом значимом действии', null=True, verbose_name='Последняя активность'),
        ),
    ]
