# Generated by Django 5.2.12 on 2026-03-22 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_last_activity_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_username', models.CharField(db_index=True, max_length=255, verbose_name='Username бота')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда кликнул')),
                ('self_confirmed_at', models.DateTimeField(blank=True, help_text='Пользователь сам нажал "Отметить ✓". Это НЕ серверная верификация.', null=True, verbose_name='Когда подтвердил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_clicks', to='users.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клик по боту',
                'verbose_name_plural': 'Клики по ботам',
                'ordering': ['-clicked_at'],
                'unique_together': {('user', 'bot_username')},
            },
        ),
    ]
