# Generated by Django 5.2.12 on 2026-03-21 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_telegramuser_bots_confirmed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('start_opened', '/start открыт'), ('gender_selection_shown', 'Выбор пола показан'), ('gender_selected', 'Пол выбран'), ('required_channels_shown', 'Каналы показаны'), ('subscription_check_clicked', 'Проверка подписки'), ('required_channels_passed', 'Каналы пройдены'), ('required_bots_shown', 'Боты показаны'), ('required_bot_confirmed', 'Бот подтверждён'), ('required_bots_passed', 'Боты пройдены'), ('main_menu_shown', 'Главное меню показано'), ('search_started', 'Поиск начат'), ('search_cancelled', 'Поиск отменён'), ('match_found', 'Пара найдена'), ('chat_started', 'Чат начат'), ('message_sent', 'Сообщение отправлено'), ('chat_finished', 'Чат завершён'), ('partner_left', 'Собеседник ушёл'), ('partner_rated', 'Собеседник оценён'), ('next_search_started', 'Следующий поиск'), ('report_sent', 'Жалоба отправлена'), ('profile_opened', 'Профиль открыт'), ('settings_opened', 'Настройки открыты'), ('how_it_works_opened', 'Как это работает')], db_index=True, max_length=64, verbose_name='Тип события')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Доп. данные: channel_id, session_id, gender и т.д.', verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FunnelSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Воронка',
                'verbose_name_plural': '📊 Воронка (сводка)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('analytics.userevent',),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['event_type', 'created_at'], name='analytics_u_event_t_2fabd2_idx'),
        ),
    ]
