# Generated by Django 5.2.12 on 2026-03-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='event_type',
            field=models.CharField(choices=[('start_opened', '/start открыт'), ('gender_selection_shown', 'Выбор пола показан'), ('gender_selected', 'Пол выбран'), ('required_channels_shown', 'Каналы показаны'), ('subscription_check_clicked', 'Проверка подписки'), ('required_channels_passed', 'Каналы пройдены'), ('required_bots_shown', 'Боты показаны'), ('required_bot_confirmed', 'Бот подтверждён'), ('required_bots_passed', 'Боты пройдены'), ('main_menu_shown', 'Главное меню показано'), ('search_started', 'Поиск начат'), ('search_cancelled', 'Поиск отменён'), ('match_found', 'Пара найдена'), ('chat_started', 'Чат начат'), ('message_sent', 'Сообщение отправлено'), ('chat_finished', 'Чат завершён'), ('partner_left', 'Собеседник ушёл'), ('partner_rated', 'Собеседник оценён'), ('next_search_started', 'Следующий поиск'), ('report_sent', 'Жалоба отправлена'), ('profile_opened', 'Профиль открыт'), ('settings_opened', 'Настройки открыты'), ('how_it_works_opened', 'Как это работает'), ('gender_change_started', 'Смена пола начата'), ('gender_changed', 'Пол изменён'), ('search_pref_change_started', 'Смена предпочтения начата'), ('search_pref_changed', 'Предпочтение изменено')], db_index=True, max_length=64, verbose_name='Тип события'),
        ),
    ]
