# Generated by Django 5.2.12 on 2026-03-18 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Описание жалобы', verbose_name='Причина')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Рассмотрена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата жалобы')),
                ('against_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='users.telegramuser', verbose_name='На кого жалоба')),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='chat.chatsession', verbose_name='Чат-сессия')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to='users.telegramuser', verbose_name='Кто пожаловался')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
                'ordering': ['-created_at'],
            },
        ),
    ]
