# Generated by Django 5.2.12 on 2026-03-18 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
            ],
            options={
                'verbose_name': 'Медиа файл',
                'verbose_name_plural': '📁 Медиа файлы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chat.message',),
        ),
    ]
